"""empty message

Revision ID: 684daca809bf
Revises: 
Create Date: 2022-12-07 18:23:27.552941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684daca809bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patiekalo_tipas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patiekalo_tipas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Patiekalo tipas', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
